name: JavaScript CI
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Test
        run: node js/src/test.js
        shell: bash
